### PR TITLE
Corrected cross compatibility

### PR DESCRIPTION
**Pull request by OsandaMalith**
eax+0x10b is wrong it should be 0xbc.

### CODE REVIEW

**Comment by b3mb4m** [comment]
Seems like u forget and eax register on 64bit :ghost:

**Comment by OsandaMalith** [comment]
The code works fine :) tested.

**Comment by b3mb4m** [comment]
unnecessary "and" on 64bit ? Just asking because of ferrie's book.Weird ~~

**Comment by OsandaMalith** [comment]
Not really. AND gate is used to unset bits. If the value is 0. 0h AND 70h =
0h.
If the value is 70h. The value is 70h AND 70h = 70h.

**Pull request merged**
